language: python
python:
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libatlas-base-dev liblapack-dev gfortran
install: travis_wait mvn install
script:
  - python setup.py install 
  - vturra 11 cs
