language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libatlas-base-dev liblapack-dev
script: python setup.py test && vturra 11 cs
